[theme]
base="light"
primaryColor="#0D6EFD"               # A clean blue
backgroundColor="#FFFFFF"           # White background
secondaryBackgroundColor="#F8F9FA"  # Light gray for sidebar/widgets
textColor="#212529"                 # Dark gray text
font="sans serif"